line.bot:
  channel-token:LqoC0ILO5AbG8JGvbxcvuDfrFTcb/pvvvFce7HFZkf5SAaMIfGNaIU0P79DydkBc1Xv8gX6Ihk8FtRH4BIKf58T1Q6/IxVFYHX/7oTZ6YWaGD3sqWTQFcABTwQJgpsqkI+QrD8Aw95j3ELDPPHYGhgdB04t89/1O/w1cDnyilFU=
  channel-secret:76f04e60cbf7b3b66f24c75c39cc1a95
  handler.path:/callback